server:
  port: 50000

spring:
  application:
    name: test-mq

  jms:
    listener:
      acknowledge-mode: auto
  redis:
    host: 127.0.0.1
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
